app_name = "airtook_video"
app_title = "AirTook Video"
app_publisher = "Etuken Idung"
app_description = "Daily.co video consult integration for AirTook"
app_email = "support@airtook.com"
app_license = "MIT"
